### ISSUE TITLE
Missing Notice: The Bot

### ISSUE THREAD

**Issue by catfo435** [UltimateSppy765/LightServerBot#4]
The bot is missing since the past few months, no sign of the bot anywhere on discord. Officials have been noted, and are investigating. As the bot owner and creator, we the people ask you, **Where is LightServerBot?** @UltimateSppy765

**Comment by UltimateSppy765** [comment]
One day, you will learn to read:
![image](https://user-images.githubusercontent.com/73820738/172679264-e74b26f2-5911-406b-9d9c-b2f2e2c00a4c.png)

**Comment by catfo435** [comment]
The Investigating Body doesn't like vague answers. Explain exactly where you hid the bot. Not doing so will automatically make you liable to legal action on behalf of the government

**Comment by UltimateSppy765** [comment]
Smh it's not a public bot.

**Comment by catfo435** [comment]
Peasant move, ngl.
